import { productList } from "types/product";

export const products:productList[] = [
    {
        image: "https://images.uzum.uz/cddm1vr5a95unf13a5h0/t_product_540_high.jpg#1687255470404",
        title: "Tagliklar Huggies Elite Soft 3, 6-11 kg, 48 dona",
        rating: 5.0,
        voices: 8,
        price: 168000,
        prev_price: 185000,
        popular: "Katta sotuvlar",
    },
    {
        image: "https://images.uzum.uz/ccg2abqbedg1tn8rk8tg/original.jpg",
        title: "Go'sht maydalagich Bosch, MFW45020",
        rating: 4.0,
        voices: 7,
        price: 142000,
        prev_price: 165000,
        popular: "Katta sotuvlar",
    },
    {
        image: "https://images.uzum.uz/cgnqra7hj8j9g69c9n50/original.jpg",
        title: "Tagliklar Huggies Elite Soft 3, 6-11 kg, 48 dona",
        rating: 5.0,
        voices: 8,
        price: 168000,
        prev_price: 185000,
        popular: "Katta sotuvlar",
    },
    {
        image: "https://images.uzum.uz/chgutabltlh4bk4jjo70/original.jpg",
        title: "Erkaklar uchun yozgi sport poyabzali",
        rating: 3.8,
        voices: 2,
        price: 92000,
        prev_price: 185000,
        popular: "Katta sotuvlar",
    },
    {
        image: "https://images.uzum.uz/ch9l0tpmaogscco7schg/original.jpg",
        title: "Krossovkalar erkaklar uchun, nafas oladigan to'rlik, sport uchun mos",
        rating: 4.2,
        voices: 42,
        price: 101000,
        prev_price: 285000,
        popular: "Katta sotuvlar",
    },
    {
        image: "https://images.uzum.uz/cgv925r57mg9720ffa5g/original.jpg",
        title: "Smartfon XIaomi Redmi Note 12 4/128GB",
        rating: 4.9,
        voices: 15,
        price: 1168000,
        prev_price: 1185000,
        popular: "Katta sotuvlar",
    },
    {
        image: "https://images.uzum.uz/ccpeikjb3ho5lmupp94g/original.jpg",
        title: "Smart tarozi Xiaomi Mi Body Composition Scale 2",
        rating: 4.0,
        voices: 25,
        price: 250000,
        prev_price: 285000,
        popular: "Katta sotuvlar",
    },
]